version: '3'
services:
  syslog-ng:
    container_name: syslog-ng
    build: .
    ports:
      - "514:514/udp"
      - "514:514"
      - "601:601"
      - "6514:6514"
    volumes:
      - syslog-ng-logs:/var/log/syslog-ng
      - syslog-ng-socket:/var/run/syslog-ng
      - syslog-ng-config:/etc/syslog-ng

volumes:
  syslog-ng-logs:
  syslog-ng-socket:
    driver_opts:
      type: none
      device: /var/run/syslog-ng
      o: bind
  syslog-ng-config:
